image: docker:latest

services:
  - docker:dind
  
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG


.build-image: &build-image
    script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .

build-master:
  stage: build
  <<: *build-image
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE"
  only:
  - master

build-branches:
  stage: build
  <<: *build-image
  except:
  - master
  - tags

build-tag:
    stage: build
    <<: *build-image
    script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    only:
    - tags